#!/bin/sh
${CVI_SHOPTS}
#
# Start firmware
#
export USERDATAPATH=/mnt/data/
export SYSTEMPATH=/mnt/system/

case "$1" in


  start)

cd /root/report
/root/report/report_loop.sh &

;;
  restart|reload)
        ;;       
  *)      
        echo "Usage: $0 {start|stop|restart}"
        exit 1                               
esac          
    
exit $?

