#!/bin/sh
${CVI_SHOPTS} 
#                                                
# Start firmware                                 
#                                                
#export USERDATAPATH=/mnt/data/                   
#export SYSTEMPATH=/mnt/system/                   

case "$1" in
  start)
      cd /root/remote-command-executor/scripts/ 
      ./poll_and_execute.sh &
    ;;
  stop)
    ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

